apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo-message
spec:
  params:
    - name: message
      type: string
      description: The message to echo
  steps:
    - name: echo
      image: alpine:3
      command:
        - /bin/echo
      args:
        - $(params.message)
