name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  build: # Job named `build`
    runs-on: ubuntu-latest # Use Ubuntu runner
    container: python:3.9-slim # Use Python container
