name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
  release:
    types:
      - published # e.g. publish Python code to PyPI, Java code to Maven, Docker container to Docker Hub, etc.
