# Workflow Composition
# - Event: Something that activates the execution of the workflow
# - Jobs: A set of tasks that execute on the same runner (jobs are named whatever you want)
#   Each job contains Runner, Services (Optional), Steps
# - Runner: The environment where the job runs (e.g. Ubuntu, Windows, macOS)
# - Steps: A sequence of tasks that execute on the same runner
# - Actions: Reusable commands that can be used in steps

name: CI workflow

# Event - `on` specifies the event that triggers the workflow
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
  release:
    types:
      - published # e.g. publish Python code to PyPI, Java code to Maven, Docker container to Docker Hub

# Jobs - `jobs` is a list of tasks that run in parallel by default
jobs:
  build: # Job named `build`
    # Runner - `runs-on` specifies the type of runner
    runs-on: ubuntu-latest # Use Ubuntu runner
    container: python:3.9-slim # Use Python container
    # Steps - `steps` is a list of commands that run in sequence
    steps:
      # Actions - `uses` specifies the action to run
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
